[features]
seeds = false
[programs.devnet]
lottery = "7MGoMVR54yM2JsoZhA4Q9ycaMDD2AC6D4ZzDRznob4k2"
[programs.localnet]
lottery = "7MGoMVR54yM2JsoZhA4Q9ycaMDD2AC6D4ZzDRznob4k2"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/jacobaune/.config/solana/id.json"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s" # implicitly also clones PwDiXFxQsGra4sFFTT8r1QWRMd4vfumiWC1jfWNfdYT


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
